"use strict";
const fs=require("node:fs");const path=require("node:path");const os=require("node:os");
const root=path.resolve(__dirname,".."),home=path.join(root,"build/elm-home"),packages=path.join(home,"0.19.2/packages");
fs.rmSync(home,{recursive:true,force:true});fs.mkdirSync(packages,{recursive:true});
const stock=path.join(os.homedir(),".elm/0.19.2/packages");for(const author of fs.readdirSync(stock)){if(author==="registry.dat"||author==="lock")continue;const src=path.join(stock,author);if(fs.statSync(src).isDirectory())fs.cpSync(src,path.join(packages,author),{recursive:true});}
function install(name,source,entries){const [author,project]=name.split("/"),dest=path.join(packages,author,project,"1.0.0");fs.mkdirSync(dest,{recursive:true});for(const entry of entries)fs.cpSync(path.join(source,entry),path.join(dest,entry),{recursive:true});}
install("sjalq/schelm-node-filesystem",root,["src","elm.json","README.md","LICENSE"]);install("sjalq/schelm-node-filesystem-fixture",path.join(root,"fixtures/package"),["src","elm.json"]);
let registry=fs.readFileSync(path.join(stock,"registry.dat"));function readEntries(buf){let pos=16,n=Number(buf.readBigUInt64BE(8)),xs=[];for(let i=0;i<n;i++){const start=pos,la=buf[pos++],author=buf.subarray(pos,pos+la).toString();pos+=la;const lp=buf[pos++],project=buf.subarray(pos,pos+lp).toString();pos+=lp;const major=buf[pos++];if(major===255)throw new Error("large version unsupported");pos+=2;const previous=Number(buf.readBigUInt64BE(pos));pos+=8+3*previous;xs.push({author,project,start});}return{n,xs};}
function add(buf,author,project){const {n,xs}=readEntries(buf),key=`${author}/${project}`;if(xs.some(x=>`${x.author}/${x.project}`===key))return buf;const index=xs.findIndex(x=>`${x.author}/${x.project}`>key),at=index<0?buf.length:xs[index].start;const entry=Buffer.concat([Buffer.from([Buffer.byteLength(author)]),Buffer.from(author),Buffer.from([Buffer.byteLength(project)]),Buffer.from(project),Buffer.from([1,0,0]),Buffer.alloc(8)]);const out=Buffer.concat([buf.subarray(0,at),entry,buf.subarray(at)]);out.writeBigUInt64BE(buf.readBigUInt64BE(0)+1n,0);out.writeBigUInt64BE(BigInt(n+1),8);return out;}
registry=add(registry,"sjalq","schelm-node-filesystem");registry=add(registry,"sjalq","schelm-node-filesystem-fixture");fs.writeFileSync(path.join(packages,"registry.dat"),registry);console.log(home);
